### PR TITLE
Add Impulse Switches and Position Sensor

### PR DESCRIPTION
**Pull request by Taraman17**
This adds impulse switches and position sensors. 

Please test thoroughly, if this does not break other switches/plugs.

### CODE REVIEW

**Comment by Taraman17** [comment]
Additional linebreaks were added by vscode automatically on saving...

**Comment by FreshlyBrewedCode** [comment]
Thanks for the PR. I am unable to test this because I am not a homee user anymore. However, the changes look good to me. If there are any problems, it is still possible to roll back to an earlier version, so no worries.

**Comment by FreshlyBrewedCode** [comment]
Actually, I just realized, we might need to make sure the latest version of pymee is included.

**Comment by Taraman17** [comment]
For me, HA installed the latest version on reboot.

**Comment by FreshlyBrewedCode** [comment]
I just bumped pymee in the manifest to the latest version so should be all good now: 90a037e

**Comment by Taraman17** [comment]
Great thanks.

When working on the code, I noticed some Deprecation notices from HA.
Is it ok, If I address these in a next step?

Don't want to work too much in your code without your approval...

**Comment by FreshlyBrewedCode** [comment]
Feel free to do whatever you want. This is open source for a reason. I don't really have any stakes in this project anymore. I will keep passively maintaining if it is not too much work. If you however are planning to make major changes that would require a lot of work to test/review I would probably encourage you to fork the project, since I won't invest too much time in this here anymore.

**Pull request merged**
