### PR TITLE
Added Sensor Support

### PR DESCRIPTION
**Pull request by Stklingner**
Currently only supports power and energy but will look at the others!

Other changes:
- Removed HomeeNodeHelper class as it was an unused class (and largely implemented by HomeeNodeEntity)
- Changed the lights module to handle nodes with multiple light attribute groups... I have some z-wave devices that have this unfortunate quality
- set naming and identifiers so that all resulting entities will be correctly attributed to the new device register entries created for each news (e.g. sensors live with their "primary" covers or lights and nodes with multiple lights are represented as a single device with multiple light entities)

ToDos: 
- replace deprecated class references (will be replaced by the StrEnums classes soon)
- make ZeroConf work again
- improve binary sensor detection -> to enable "add all nodes"
- investigate weird intermittent disconnection issue
- add other sensor classes (e.g. temp/humidity)
- add complicated sensor classes (e.g. smoke detection)
- add homee brain cube sensors

### CODE REVIEW

**Comment by Stklingner** [comment]
Hold the pull request - I still have a small bug in the entity naming

**Comment by FreshlyBrewedCode** [comment]
Is this now ready to be merged?

**Comment by Stklingner** [comment]
Should be good now!

**Comment by FreshlyBrewedCode** [comment]
I squash-merged your last PR and we have duplicate commits. Could you rebase from [5c46e53](https://github.com/FreshlyBrewedCode/hacs-homee/pull/14/commits/5c46e53833e8fd6189cb6a4fd8e0ee7b859e11d7) on master (I think this is the first new commit)?

**Comment by Stklingner** [comment]
I think I sorted it out - for some reason Working Copy on my iPad doesn't play well with others.

**Comment by FreshlyBrewedCode** [comment]
It has somehow gotten more confusing. I mainly see the commits from the last PR now in the history. There are also still merge conflicts. Make sure you pull the latest version from this repo and then either rebase or merge your changes.

**Comment by Stklingner** [comment]
Sorry - will tidy it up and submit a new PR; cancel this one for now!On 10 Oct 2022, at 7:23 pm, Karl Möller ***@***.***> wrote:﻿
It has somehow gotten more confusing. I mainly see the commits from the last PR now in the history. There are also still merge conflicts. Make sure you pull the latest version from this repo and then either rebase or merge your changes.

**Comment by FreshlyBrewedCode** [comment]
No worries, just trying to keep the history clean. Git can be confusing sometimes especially since the CI also adds new commits for the releases.

**Pull request closed without merging**
